
version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/votedb
      - NODE_ENV=development
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
      - MAIL_FROM=noreply@votesystem.com
      - JWT_SECRET=your_jwt_secret_key_change_in_production

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=votedb
    ports:
      - "5432:5432"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP server

volumes:
  postgres_data:
