
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { LogEntry } from './types';
import { logService } from './logService';

// Mock admin data for authentication purposes
const mockAdmins = [
  {
    id: '1',
    name: 'Admin User',
    email: 'admin@example.com',
    role: 'admin'
  },
  {
    id: '2',
    name: 'Super Admin',
    email: 'super@example.com',
    role: 'super_admin'
  }
];

export const loginAdmin = async (email: string, password: string) => {
  // Mock login for admin users
  const admin = mockAdmins.find(admin => admin.email === email);
  
  if (admin && password === 'password') {  // Simple password check for mocking purposes
    // Create log entry for successful login
    try {
      await logService.addLog(
        admin.id,
        admin.name,
        'LOGIN',
        `Admin user ${admin.email} logged in`
      );
    } catch (error) {
      console.error("Error logging admin login:", error);
    }
    
    // Store user info in localStorage
    localStorage.setItem('user', JSON.stringify({
      id: admin.id,
      name: admin.name,
      email: admin.email,
      role: admin.role
    }));
    
    return true;
  }
  
  return false;
};

export const logoutAdmin = async (userId: string, userName: string) => {
  // Create log entry for logout
  try {
    await logService.addLog(
      userId,
      userName,
      'LOGOUT',
      `Admin user ${userName} logged out`
    );
  } catch (error) {
    console.error("Error logging logout:", error);
  }
  
  // Clear user info from localStorage
  localStorage.removeItem('user');
};
